require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SongPartsController do

  # This should return the minimal set of attributes required to create a valid
  # SongPart. As you add validations to SongPart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "part_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SongPartsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all song_parts as @song_parts" do
      song_part = SongPart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:song_parts).should eq([song_part])
    end
  end

  describe "GET show" do
    it "assigns the requested song_part as @song_part" do
      song_part = SongPart.create! valid_attributes
      get :show, {:id => song_part.to_param}, valid_session
      assigns(:song_part).should eq(song_part)
    end
  end

  describe "GET new" do
    it "assigns a new song_part as @song_part" do
      get :new, {}, valid_session
      assigns(:song_part).should be_a_new(SongPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested song_part as @song_part" do
      song_part = SongPart.create! valid_attributes
      get :edit, {:id => song_part.to_param}, valid_session
      assigns(:song_part).should eq(song_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SongPart" do
        expect {
          post :create, {:song_part => valid_attributes}, valid_session
        }.to change(SongPart, :count).by(1)
      end

      it "assigns a newly created song_part as @song_part" do
        post :create, {:song_part => valid_attributes}, valid_session
        assigns(:song_part).should be_a(SongPart)
        assigns(:song_part).should be_persisted
      end

      it "redirects to the created song_part" do
        post :create, {:song_part => valid_attributes}, valid_session
        response.should redirect_to(SongPart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved song_part as @song_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        SongPart.any_instance.stub(:save).and_return(false)
        post :create, {:song_part => { "part_id" => "invalid value" }}, valid_session
        assigns(:song_part).should be_a_new(SongPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SongPart.any_instance.stub(:save).and_return(false)
        post :create, {:song_part => { "part_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested song_part" do
        song_part = SongPart.create! valid_attributes
        # Assuming there are no other song_parts in the database, this
        # specifies that the SongPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SongPart.any_instance.should_receive(:update_attributes).with({ "part_id" => "1" })
        put :update, {:id => song_part.to_param, :song_part => { "part_id" => "1" }}, valid_session
      end

      it "assigns the requested song_part as @song_part" do
        song_part = SongPart.create! valid_attributes
        put :update, {:id => song_part.to_param, :song_part => valid_attributes}, valid_session
        assigns(:song_part).should eq(song_part)
      end

      it "redirects to the song_part" do
        song_part = SongPart.create! valid_attributes
        put :update, {:id => song_part.to_param, :song_part => valid_attributes}, valid_session
        response.should redirect_to(song_part)
      end
    end

    describe "with invalid params" do
      it "assigns the song_part as @song_part" do
        song_part = SongPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SongPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => song_part.to_param, :song_part => { "part_id" => "invalid value" }}, valid_session
        assigns(:song_part).should eq(song_part)
      end

      it "re-renders the 'edit' template" do
        song_part = SongPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SongPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => song_part.to_param, :song_part => { "part_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested song_part" do
      song_part = SongPart.create! valid_attributes
      expect {
        delete :destroy, {:id => song_part.to_param}, valid_session
      }.to change(SongPart, :count).by(-1)
    end

    it "redirects to the song_parts list" do
      song_part = SongPart.create! valid_attributes
      delete :destroy, {:id => song_part.to_param}, valid_session
      response.should redirect_to(song_parts_url)
    end
  end

end
